version: '3'
services:
  be_express:
    container_name: 'be_express'
    build: ./be_express/
    ports:
      - '3001:3001'
    environment:
      PGHOST: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'anything'
      PGPORT: '5432'
      EXPRESS_TYPEORM_PGDATABASE: 'forensic_truth'
  pg:
    image: 'postgres:12'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'anything'
      POSTGRES_DB: 'forensic_truth'
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
  fe_react:
    container_name: 'fe_react'
    build: ./fe_react/
    ports:
      - '3000:3000'
